<?xml version="1.0" encoding="UTF-8"?>
<!-- Ideally this file wouldn't be here.  It currently exists to prevent Hibernate from throwing an exception during initialization. -->
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
    <persistence-unit name="PU">
     <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
            <class>beans.CulturalEvent</class>
            <class>beans.Location</class>
            <properties>
                <property name="hibernate.connection.url" value="jdbc:mysql://localhost:3306/test"/>
                <property name="hibernate.connection.driver_class" value="com.mysql.cj.jdbc.Driver"/>
                <property name="hibernate.connection.username" value="root"/>
                <property name="hibernate.connection.password" value="venu23"/>
                <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect" />
                <property name="hibernate.archive.autodetection" value="class"/>
                <property name="hibernate.show_sql" value="true"/>
                <property name="hibernate.format_sql" value="true"/>
                <property name="hbm2ddl.auto" value="update"/>
            </properties>
    </persistence-unit>
</persistence>
